### Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: <ваш vault-token>
type: Opaque

### Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson