---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sausagestore-configmap
data:
  sausagestore.conf: |
    server {

      listen 8080;

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://backend:8080;
      }
    }
